openapi: "3.0.0"
info:
  version: 1.3.0
  title: orders-api
  description: "Order management API"

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        customer_email:
          type: string
        order_date:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - open
            - close
        total_amount:
          type: number
      required:
        - id
        - customer_email
        - order_date
        - status
        - total_amount

paths:
  /orders:
    get:
      responses:
        "200":
          description: returns all orders for a customer
          content:
            application/json:
              schema:
                type: object
                properties:
                  next:
                    type: string
                  count:
                    type: number
                  orders:
                    type: array
                    items:
                      $ref: "#/components/schemas/Order"
  /orders/{id}:
    get:
      responses:
        "200":
          description: individual order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
                  code:
                    type: string
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: updates an order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"